// Wildlife data voor reis naar Frankrijk
// Regio's: lozere, cantal, pyrenees
// Zeldzaamheid: 1 = veel voorkomend, 2 = ongewoon, 3 = zeldzaam
// Categorieën: roofvogel, zoogdier, reptiel_amfibie, insect

export const wildlifeData = [
  // ============================================
  // ROOFVOGELS
  // ============================================
  {
    id: 'vale-gier',
    naam: 'Vale gier',
    duits: 'Gänsegeier',
    latijn: 'Gyps fulvus',
    wiki: 'Griffon_vulture',
    kenmerken: 'Gele/witte kraag, zandkleurig lichaam. Vliegt met horizontale vleugels en opengesperde "vingers". Enorme spanwijdte tot 2.8m.',
    waar_wanneer: 'Honderden broedparen bij Gorges de la Jonte en Tarn. Vooral halverwege de ochtend als de thermiek begint, hoog in de lucht te zien in groepen (spiralend).',
    categorie: 'roofvogel',
    regios: ['lozere', 'pyrenees'],
    zeldzaamheid: 1,
    geluid: 'https://xeno-canto.org/species/Gyps-fulvus',
  },
  {
    id: 'lammergier',
    naam: 'Lammergier',
    duits: 'Bartgeier',
    latijn: 'Gypaetus barbatus',
    wiki: 'Bearded_vulture',
    kenmerken: 'Puntige ruitvormige staart. Roestkleurige borst en witte kop met prominente zwarte maskerstreep / baard.',
    waar_wanneer: 'Vliegt langs steile rotswanden en bergtoppen in de hoge Pyrénées. Kan op elk moment van de dag gezien worden als de zon schijnt op de kalkstenen kliffen.',
    categorie: 'roofvogel',
    regios: ['pyrenees'],
    zeldzaamheid: 3,
    geluid: 'https://xeno-canto.org/species/Gypaetus-barbatus',
  },
  {
    id: 'monniksgier',
    naam: 'Monniksgier',
    duits: 'Mönchsgeier',
    latijn: 'Aegypius monachus',
    wiki: 'Cinereous_vulture',
    kenmerken: 'Donker (bijna zwart) verenkleed. Nog groter dan vale gier (spanwijdte tot 3m). Zeer rechthoekig vliegbeeld met vlakke vleugels.',
    waar_wanneer: 'Wordt vaak solitair of met een vale gier-groep gezien boven de Causses in de vroege middag.',
    categorie: 'roofvogel',
    regios: ['lozere'],
    zeldzaamheid: 3,
    geluid: 'https://xeno-canto.org/species/Aegypius-monachus',
  },
  {
    id: 'aasgier',
    naam: 'Aasgier',
    duits: 'Schmutzgeier',
    latijn: 'Neophron percnopterus',
    wiki: 'Egyptian_vulture',
    kenmerken: 'Wit verenkleed met sterk afstekende zwarte vleugelranden. Felgele kale gezichtshuid. Klein en wendbaarder dan andere gieren.',
    waar_wanneer: 'Alleen in mei-september. Te spotten bij kadavers of biddend over de warme weilanden langs kalksteenwanden van Gorges du Tarn.',
    categorie: 'roofvogel',
    regios: ['lozere', 'pyrenees'],
    zeldzaamheid: 3,
    geluid: 'https://xeno-canto.org/species/Neophron-percnopterus',
  },
  {
    id: 'rode-wouw',
    naam: 'Rode wouw',
    duits: 'Rotmilan',
    latijn: 'Milvus milvus',
    wiki: 'Red_kite',
    kenmerken: 'Elegante roodbruine roofvogel, sterk en diep gevorkte staart. Grote witte schuine vlekken ("vensters") aan onderkant van vleugelpunten.',
    waar_wanneer: 'Talrijk aanwezig overal boven de weidevlaktes, de hele dag door, met name Cantal en Margeride. Vaak op zoek naar dode dieren langs wegen.',
    categorie: 'roofvogel',
    regios: ['lozere', 'cantal'],
    zeldzaamheid: 1,
    geluid: 'https://xeno-canto.org/species/Milvus-milvus',
  },
  {
    id: 'steenarend',
    naam: 'Steenarend',
    duits: 'Steinadler',
    latijn: 'Aquila chrysaetos',
    wiki: 'Golden_eagle',
    kenmerken: 'Aanzienlijk uniform donkerbruin. Goudgele waas op de achterhoofdveren in goed licht. In de vlucht houden ze vleugels vaak in lichte V-vorm opgetild.',
    waar_wanneer: 'Hoge bergwanden, open vallei-gebieden, net buiten thermiekuren. Meestal eenzaam (of in paar) scannend naar marmotten vanaf grote hoogte.',
    categorie: 'roofvogel',
    regios: ['pyrenees', 'lozere'],
    zeldzaamheid: 2,
    geluid: 'https://xeno-canto.org/species/Aquila-chrysaetos',
  },
  {
    id: 'slangenarend',
    naam: 'Slangenarend',
    duits: 'Schlangenadler',
    latijn: 'Circaetus gallicus',
    wiki: 'Short-toed_snake_eagle',
    kenmerken: 'Zeer lichte, soms spierwitte onderkant van lichaam en buik, gebandeerde staart. Opvallend grote en brede (uil-achtige) kop.',
    waar_wanneer: 'Gedurende hete uren speurend en "biddend" boven droge, stenige hellingen met struiken waar ringslangen kruipen.',
    categorie: 'roofvogel',
    regios: ['lozere', 'cantal', 'pyrenees'],
    zeldzaamheid: 2,
    geluid: 'https://xeno-canto.org/species/Circaetus-gallicus',
  },
  {
    id: 'blauwe-kiekendief',
    naam: 'Blauwe kiekendief',
    duits: 'Kornweihe',
    latijn: 'Circus cyaneus',
    wiki: 'Hen_harrier',
    kenmerken: 'Mannetje: parelgrijs, wit acherlijf en zwarte vleugelpunten ("spook"). Vrouwtje: bruin gestreept, markante witte vlek aan staartbasis. Vliegen in V-houding.',
    waar_wanneer: 'Open heide en moerassige dalen in halfopen vlaktes van de Auvergne (Cantal). Vaak extreem laag zigzaggend kort over de grond bij zonsondergang.',
    categorie: 'roofvogel',
    regios: ['cantal'],
    zeldzaamheid: 2,
    geluid: 'https://xeno-canto.org/species/Circus-cyaneus',
  },
  {
    id: 'oehoe',
    naam: 'Oehoe',
    duits: 'Uhu',
    latijn: 'Bubo bubo',
    wiki: 'Eurasian_eagle-owl',
    kenmerken: 'Europese "tijger van de nacht". Enorm groot profiel, stijve grote "oorpluimen" boven op kop en fel oranje, glurende ogen.',
    waar_wanneer: 'Nachtdier en verborgen in kloven overdag. Meeste kans in diepe schemering als robuuste donkere vlek langs steile kalkwanden Gorges du Tarn.',
    categorie: 'roofvogel',
    regios: ['lozere'],
    zeldzaamheid: 2,
    geluid: 'https://xeno-canto.org/species/Bubo-bubo',
  },

  // ============================================
  // ANDERE VOGELS
  // ============================================
  {
    id: 'alpenkraai',
    naam: 'Alpenkraai',
    duits: 'Alpenkrähe',
    latijn: 'Pyrrhocorax pyrrhocorax',
    wiki: 'Red-billed_chough',
    kenmerken: 'Geheel gitzwarte veren. Opvallend dunne, neerwaarts gekromde felrode snavel en donkerrode poten.',
    waar_wanneer: 'Korte grasweides, klippen langs bergkammen. Uiterst acrobatisch spelevliegen waarbij ze zich met gestrekte vleugels door vlagen laten rondsmijten.',
    categorie: 'roofvogel',
    regios: ['cantal', 'pyrenees'],
    zeldzaamheid: 2,
    geluid: 'https://xeno-canto.org/species/Pyrrhocorax-pyrrhocorax',
  },
  {
    id: 'fluiter',
    naam: 'Fluiter',
    duits: 'Waldlaubsänger',
    latijn: 'Phylloscopus sibilatrix',
    wiki: 'Wood_warbler',
    kenmerken: 'Heldere gele (bijna limoen) oogstreep, en een zuiver witte buik die scherp contrasteert met opvallende geelgroene rug en borst.',
    waar_wanneer: 'Diep verborgen boven in de lianen van pure loofbossen en oud eiken-/beukenbos aan de randen van Cevennen dalen. Trillende metaal-achtige zang verraadt hem.',
    categorie: 'roofvogel',
    regios: ['lozere'],
    zeldzaamheid: 2,
    geluid: 'https://xeno-canto.org/species/Phylloscopus-sibilatrix',
  },
  {
    id: 'sneeuwvink',
    naam: 'Sneeuwvink',
    duits: 'Schneefink',
    latijn: 'Montifringilla nivalis',
    wiki: 'White-winged_snowfinch',
    kenmerken: 'Gitzwarte slabbetje aan grijze kraagkop, en dramatisch uitgebreid wit in vleugels opflitsend tijdens vlucht (lijkt dan op een sneeuwvlokje).',
    waar_wanneer: 'Leeft uitsluitend hoog in het uiterste Pyreneeën gebergte (boven 2000 m!), vaak hippen ze dicht nabij alpine berghutten zoekend naar weggewaaide broodkruimels.',
    categorie: 'roofvogel',
    regios: ['pyrenees'],
    zeldzaamheid: 2,
    geluid: 'https://xeno-canto.org/species/Montifringilla-nivalis',
  },
  {
    id: 'sneeuwhoen',
    naam: 'Sneeuwhoen',
    duits: 'Alpenschneehuhn',
    latijn: 'Lagopus muta',
    wiki: 'Rock_ptarmigan',
    kenmerken: 'Perfect gecamoufleerde, forse hoendervogel. In de zomer is die gespikkeld rotsgrijs met zandbruin. Witte buik direct onder het grauwe bovendeel.',
    waar_wanneer: 'Ver weg buiten het zomer-toerisme spoor, boven 2200m op dorre en stenige kammen. Bevriest perfect waardoor je hem vaak pas op een paar meter ziet.',
    categorie: 'roofvogel',
    regios: ['pyrenees'],
    zeldzaamheid: 3,
    geluid: 'https://xeno-canto.org/species/Lagopus-muta',
  },
  {
    id: 'middelste-bonte-specht',
    naam: 'Witrugspecht',
    duits: 'Weißrückenspecht',
    latijn: 'Dendrocopos leucotos',
    wiki: 'White-backed_woodpecker',
    kenmerken: 'Licht afgeronde vlek op het achterwerk en kenmerkend wit streepjes-"laddertje" overheen de rug en onderkant met lange snavel. Zachte snelle roffels',
    waar_wanneer: 'Aangewezen op de oerkwaliteit van bebossing. Lang de berghellingen aan puur oude, soms decennia rottende bomen nabij ongerepte gebieden Pyrénées.',
    categorie: 'roofvogel',
    regios: ['pyrenees'],
    zeldzaamheid: 3,
    geluid: 'https://xeno-canto.org/species/Dendrocopos-leucotos',
  },

  // ============================================
  // ZOOGDIEREN
  // ============================================
  {
    id: 'marmot',
    naam: 'Marmot',
    duits: 'Alpenmurmeltier',
    latijn: 'Marmota marmota',
    wiki: 'Alpine_marmot',
    kenmerken: 'Forse bouwwerk verplaatsende, oer-gezellige mollige bergknagers met geelgrijze tot bruine pluisvacht en korte snuit. Korte wakkere oortjes.',
    waar_wanneer: 'Zodra de sneeuw goed gesmolten is lopen ze langs bergalmen en rotschaos van Cantal Puy Mary of Pyreneeën paden. Bij gevaar schiet extreem hard hoog fluitje als brandalarm op.',
    categorie: 'zoogdier',
    regios: ['cantal', 'pyrenees'],
    zeldzaamheid: 1,
    geluid: null,
  },
  {
    id: 'gems',
    naam: 'Gems',
    duits: 'Gämse',
    latijn: 'Rupicapra rupicapra',
    wiki: 'Chamois',
    kenmerken: 'Twee slanke, korte bijna pikzwarte "haak"-hoorntjes die verticaal iets ombuigen aan het einde. Geliggende, afstekende witte tekeningen dwars over snoetjes',
    waar_wanneer: 'Soepel springend tussen zeer verradelijk vulkaanrots bij Cantal, hoog boven de boomgrens gedurende de dauwmomenten of in koele avonden.',
    categorie: 'zoogdier',
    regios: ['cantal'],
    zeldzaamheid: 2,
    geluid: null,
  },
  {
    id: 'isard',
    naam: 'Isard (Pyrenese gems)',
    duits: 'Pyrenäen-Gämse',
    latijn: 'Rupicapra pyrenaica',
    wiki: 'Pyrenean_chamois',
    kenmerken: 'Iets ieler, zandkleuriger en korter uitgevallen zomervacht dan reguliere gems. Meest in oog springend door een doorzette brede zwarte, "vlakke kraag"- streep over nekjes',
    waar_wanneer: 'Meestal in weides flanerend tegen steile rotswanden of ver over hoogtemeters de stenen bevolkend in het onvergevingsgezinde oosten van het Pyreneeën massief',
    categorie: 'zoogdier',
    regios: ['pyrenees'],
    zeldzaamheid: 2,
    geluid: null,
  },
  {
    id: 'moeflon',
    naam: 'Moeflon',
    duits: 'Mufflon',
    latijn: 'Ovis gmelini musimon',
    wiki: 'Mouflon',
    kenmerken: 'Volwassen mannetjes (rammen) dragen ongelooflijke, zware hoorns die robuust opzij over gitzwarte wangen een cirkel omlaag naar boven dwingen.',
    waar_wanneer: 'Voorzichtig wandelend over korte bloemenweides die op hellingen of bergpaden langs bosranden lopen. Makkelijker te traceren op randuurtjes in de vroege vroege morgen.',
    categorie: 'zoogdier',
    regios: ['cantal', 'pyrenees'],
    zeldzaamheid: 2,
    geluid: null,
  },
  {
    id: 'edelhert',
    naam: 'Edelhert',
    duits: 'Rothirsch',
    latijn: 'Cervus elaphus',
    wiki: 'Red_deer',
    kenmerken: 'Hoge lange schouderlijn (grootst robuuste Europese hoefdier). Mannetjes toornen trots wijdse, indrukwekkende vertakte kruinen, zeker eindzomers prachtig bruin vol uitgehard',
    waar_wanneer: 'Verdwijnt perfect geluidloos diep doorn dichtbeboste bergbossen buiten paarmaand. September is burhmaand; testosteron-gedreven brul is dan over Pyrenese bergruggen uren ver te traceren',
    categorie: 'zoogdier',
    regios: ['pyrenees'],
    zeldzaamheid: 2,
    geluid: null,
  },
  {
    id: 'europese-genet',
    naam: 'Europese genet',
    duits: 'Kleinfleck-Ginsterkatze',
    latijn: 'Genetta genetta',
    wiki: 'Common_genet',
    kenmerken: 'Licht grijpende "wasbeer"achtige kat-soort in Frankrijk geïntroduceerd vroeger. Extreem lang rekbare cilindrische lange ringstaart versierd met dik 8-10 donkere banden.',
    waar_wanneer: 'Extreem heimelijk uitsluitend als holst v/d nacht-predator. Verblijft om verlaten boerenschuren, grotten deels kalkvlaktes, of klimmen zomers door dichte boomtop luifels',
    categorie: 'zoogdier',
    regios: ['lozere', 'pyrenees'],
    zeldzaamheid: 3,
    geluid: null,
  },
  {
    id: 'bruine-beer',
    naam: 'Bruine beer',
    duits: 'Braunbär',
    latijn: 'Ursus arctos',
    wiki: 'Brown_bear',
    kenmerken: 'Log, rond compact zoogdier en indrukwekkende vacht. Uitgesproken grote schouderbult is direct onderscheidend',
    waar_wanneer: 'Herintroduceert met moeite diepste uitgestrekte Pyreneegebergte maar zwerft immens. Vrij onmogelijk wild the observeren; uitwerpselen / kapot gewielde boomstronken wijzen indirect diens aanwezigheid soms aan',
    categorie: 'zoogdier',
    regios: ['pyrenees'],
    zeldzaamheid: 3,
    geluid: null,
  },
  {
    id: 'desman',
    naam: 'Pyrenese desman',
    duits: 'Pyrenäen-Desman',
    latijn: 'Galemys pyrenaicus',
    wiki: 'Pyrenean_desman',
    kenmerken: 'Uniek bizar schepsel: plat rat-achtig lijf maar met grote zilverwang, piepkleine ogen en bovenal een trompetterig ver en bizar prehistorisch snuitje dat tastend water beweegt.',
    waar_wanneer: 'Leeft amper boven koud, helder en wild zuurstofrijk smeltwater stromend van Pyrenee piepdonker en is absoluut overdag verzonken in spelonken weggedoken. Ongeëvenaard "lucky catch".',
    categorie: 'zoogdier',
    regios: ['pyrenees'],
    zeldzaamheid: 3,
    geluid: null,
  },
  {
    id: 'hermelijn',
    naam: 'Hermelijn',
    duits: 'Hermelin',
    latijn: 'Mustela erminea',
    wiki: 'Stoat',
    kenmerken: 'Roestbruin soepel glij-lang lichaam omlijst aan een helder gladde buik en pootjes maar onderscheidt feiloos door één gitzwart einde als punt van zn staart.',
    waar_wanneer: 'Tafereelt razendsnel onrust tussen of in traditionele Franse stapelmuren nabij grasvlakten onder de Franse vulkanen in jacht na knaagdieren of uit curiositeit op twee poten peilend',
    categorie: 'zoogdier',
    regios: ['cantal'],
    zeldzaamheid: 2,
    geluid: null,
  },
  {
    id: 'europese-bever',
    naam: 'Europese bever',
    duits: 'Europäischer Biber',
    latijn: 'Castor fiber',
    wiki: 'Eurasian_beaver',
    kenmerken: 'Plat geslepen massieve haarloze "pannenkoekstaart" slaat keihard water op om alarm af te geven, verder stomp rond en nat door de rivier schietend in schemer.',
    waar_wanneer: 'Wandelt soms schemerig op de oeverranden onder the overkapping van Gorges du Tarn om lange bomen af te knagen voor winter of veiliger te dammen ten behoefte kreekjes',
    categorie: 'zoogdier',
    regios: ['lozere'],
    zeldzaamheid: 2,
    geluid: null,
  },
  {
    id: 'europese-nerts',
    naam: 'Europese nerts',
    duits: 'Europäischer Nerz',
    latijn: 'Mustela lutreola',
    wiki: 'European_mink',
    kenmerken: 'Donker chocolade effen tot bijna zwartig dier afgetekend als rovers, maar specifieke verhullend door 1 unieke contrasterende compleet helderwitte strook vacht over lip alsook boven.',
    waar_wanneer: 'Overleeft maar nèt via kweek programmas weggestopt in traag slibberende beek-bossen of broeken met dicht riet overwoekerd langs Aquitaine en uiterste westelijke departementen',
    categorie: 'zoogdier',
    regios: ['pyrenees'],
    zeldzaamheid: 3,
    geluid: null,
  },
  {
    id: 'przewalskipaard',
    naam: 'Przewalskipaard',
    duits: 'Przewalski-Pferd',
    latijn: 'Equus ferus przewalskii',
    wiki: 'Przewalski\'s_horse',
    kenmerken: 'Plomp woest paard voorzien oerkleuren isabel. Echte herkenning uit manen, ze pronken recht borstelig naar boven over de hals zonder val tot snuit met opvallende aalstreep',
    waar_wanneer: 'Deze kudde is uniek gevestigd wild in beschermd domeingebied weggesloten over de desolate steppe-achtige Causse Méjean; ze overzien strak verkleurende valleien',
    categorie: 'zoogdier',
    regios: ['lozere'],
    zeldzaamheid: 2,
    geluid: null,
  },

  // ============================================
  // REPTIELEN & AMFIBIEËN
  // ============================================
  {
    id: 'vuursalamander',
    naam: 'Vuursalamander',
    duits: 'Feuersalamander',
    latijn: 'Salamandra salamandra',
    wiki: 'Fire_salamander',
    kenmerken: 'Huid ademt zwaar zwart parelend glans maar schreeuwt direct gif met enorm spetterende banen of plassen fel goudgele vlekken en trage koddige wandelgang',
    waar_wanneer: 'Bedompte donkere uren als plots druilregens bosbodem natter dan bedauwd opleveren in dichtbeboste eikenwoud onderzijde ravijnen in de zuid- Lozère dalen',
    categorie: 'reptiel_amfibie',
    regios: ['lozere'],
    zeldzaamheid: 1,
    geluid: null,
  },
  {
    id: 'alpenwatersalamander',
    naam: 'Alpenwatersalamander',
    duits: 'Bergmolch',
    latijn: 'Ichthyosaura alpestris',
    wiki: 'Alpine_newt',
    kenmerken: 'De man is verbluffend versierd in lenteperiode - felle fel oranje gloeiende weke buiken combineren tegen marmerblauw donker en witte vlekflanken ',
    waar_wanneer: 'Duik met zaklamp (gedempte zon uren) diepe helder staande bosmeertjes nabij gletsjer-achtergebleven diepe kommen van massifs zo ook hoger liggende Cantal poelen',
    categorie: 'reptiel_amfibie',
    regios: ['cantal'],
    zeldzaamheid: 2,
    geluid: null,
  },
  {
    id: 'muurhagedis',
    naam: 'Muurhagedis',
    duits: 'Mauereidechse',
    latijn: 'Podarcis muralis',
    wiki: 'Common_wall_lizard',
    kenmerken: 'Heel lang gespieste smalle ratel-staart aan extreem afgeplatte lichte olijf en stenen-grijze schubbetjes en diepliggend donker masker strepend richting lange nek.',
    waar_wanneer: 'Dagen de thermometer over klimmende graden tipt vult elke hoek van eeuwenoude landschaps gebonden stapel muren vol krioelende warmte zoekende sprinters',
    categorie: 'reptiel_amfibie',
    regios: ['lozere', 'cantal', 'pyrenees'],
    zeldzaamheid: 1,
    geluid: null,
  },

  // ============================================
  // INSECTEN
  // ============================================
  {
    id: 'apollovlinder',
    naam: 'Apollovlinder',
    duits: 'Roter Apollo',
    latijn: 'Parnassius apollo',
    wiki: 'Apollo_(butterfly)',
    kenmerken: 'Gigantisch papier doorschijnend en langgerekt zweven onder extreem opmerkelijke zware helder rood met zwart randige pupillen (ogen) gesierd op het achterste en rond vleugel part',
    waar_wanneer: 'Dwarrelt rustig en flappend met grote trage spanne langs met zon beschenen diepe rotsig of vetplant achtige bloemen en bloedhete kloof hellingen zuidelijker bergen in bloeitijd mei-juni',
    categorie: 'insect',
    regios: ['cantal', 'pyrenees'],
    zeldzaamheid: 2,
    geluid: null,
  },
  {
    id: 'europese-wolfspin',
    naam: 'Europese wolfspin',
    duits: 'Apulische Tarantel',
    latijn: 'Lycosa tarantula',
    wiki: 'Lycosa_tarantula',
    kenmerken: 'Massieve tot drie-centimeter lange romp, dik gedrongen gestreept pootbeslag voorzien zwaar diepte zichts oplichten in de nachtelijke acht-oog reflex.',
    waar_wanneer: 'Maakt uiterst effectieve hinderlaag netten plat liggende rotsvlakken, op zoek over droge zand of kalkgras steen plateaus Cevennen (onder stenen) waar ze wacht tot trilling nadert',
    categorie: 'insect',
    regios: ['lozere'],
    zeldzaamheid: 2,
    geluid: null,
  },

  // ============================================
  // BIJZONDER: PYRENESE GEMS-BOK
  // ============================================
  {
    id: 'pyrenese-steenbok',
    naam: 'Pyrenese steenbok',
    duits: 'Iberiensteinbock',
    latijn: 'Capra pyrenaica victoriae',
    wiki: 'Iberian_ibex',
    kenmerken: 'Nauwkeurige sik, maar dominant bestempeld met gigantische massieve scherp gekartelde geboge donkere gehoorns welke boog afwenden zijdens de ribbenkas.',
    waar_wanneer: 'Wandelen statig ver boven grens verwaaide rots toppen diepe west-Pyrenee regio (voor de klimmers!). Moeilijke vindbaarheid aangezien recente introductie langzame kuddengroei oplevert',
    categorie: 'zoogdier',
    regios: ['pyrenees'],
    zeldzaamheid: 3,
    geluid: null,
  },
];

// Categorie labels en emoji's
export const categorieLabels = {
  roofvogel: { label: 'Vogels', emoji: '\u{1F986}' },
  zoogdier: { label: 'Zoogdieren', emoji: '\u{1F98C}' },
  reptiel_amfibie: { label: 'Reptielen & amfibie\u00EBn', emoji: '\u{1F98E}' },
  insect: { label: 'Insecten & spinnen', emoji: '\u{1F98B}' },
};

// Regio labels en emoji's
export const regioLabels = {
  lozere: { label: 'Loz\u00E8re', emoji: '\u{1F3D4}\uFE0F' },
  cantal: { label: 'Cantal', emoji: '\u{1F30B}' },
  pyrenees: { label: 'Pyr\u00E9n\u00E9es', emoji: '\u{1F43B}' },
};

// Zeldzaamheid labels
export const zeldzaamheidLabels = {
  1: { label: 'Veel voorkomend', emoji: '\u2B50', kleur: '#4CAF50' },
  2: { label: 'Ongewoon', emoji: '\u2B50\u2B50', kleur: '#FF9800' },
  3: { label: 'Zeldzaam', emoji: '\u2B50\u2B50\u2B50', kleur: '#F44336' },
};
