// Wildlife data voor reis naar Frankrijk
// Regio's: lozere, cantal, pyrenees
// Zeldzaamheid: 1 = veel voorkomend, 2 = ongewoon, 3 = zeldzaam
// Categorieën: roofvogel, zoogdier, reptiel_amfibie, insect

export const wildlifeData = [
  // ============================================
  // ROOFVOGELS
  // ============================================
  {
    id: 'vale-gier',
    naam: 'Vale gier',
    frans: 'Vautour fauve',
    wiki: 'Griffon_vulture',
    info: 'Grootste gier van de Causses, spanwijdte tot 2,7m. Honderden broedparen bij Gorges de la Jonte.',
    categorie: 'roofvogel',
    regios: ['lozere', 'pyrenees'],
    zeldzaamheid: 1,
    tip: 'Gorges de la Jonte bij Maison des Vautours. Ochtend als thermiek opkomt.',
    geluid: 'https://xeno-canto.org/species/Gyps-fulvus',
  },
  {
    id: 'lammergier',
    naam: 'Lammergier',
    frans: 'Gypaète barbu',
    wiki: 'Bearded_vulture',
    info: 'Iconisch: dropt botten op rotsen om het merg te eten. Spanwijdte 2,8m. Oranje borst.',
    categorie: 'roofvogel',
    regios: ['pyrenees'],
    zeldzaamheid: 3,
    tip: 'Hoge Pyrénées, kijk bij kliffen en ravijnen. Vroege ochtend, alleen boven 1500m.',
    geluid: 'https://xeno-canto.org/species/Gypaetus-barbatus',
  },
  {
    id: 'monniksgier',
    naam: 'Monniksgier',
    frans: 'Vautour moine',
    wiki: 'Cinereous_vulture',
    info: 'Grootste Europese roofvogel, spanwijdte tot 3m. Herintroductie in de Causses sinds 1992.',
    categorie: 'roofvogel',
    regios: ['lozere'],
    zeldzaamheid: 3,
    tip: 'Causses, vaak samen met vale gieren. Herkenbaar aan donkere kleur en platte vluchtsilhouet.',
    geluid: 'https://xeno-canto.org/species/Aegypius-monachus',
  },
  {
    id: 'aasgier',
    naam: 'Aasgier',
    frans: 'Vautour percnoptère',
    wiki: 'Egyptian_vulture',
    info: 'Kleinste Europese gier. Wit met zwarte vleugelpunten. Trekt in winter naar Afrika.',
    categorie: 'roofvogel',
    regios: ['lozere', 'pyrenees'],
    zeldzaamheid: 3,
    tip: 'Mei-september. Gorges du Tarn en Pyrénées kliffen. Vaak in paren.',
    geluid: 'https://xeno-canto.org/species/Neophron-percnopterus',
  },
  {
    id: 'rode-wouw',
    naam: 'Rode wouw',
    frans: 'Milan royal',
    wiki: 'Red_kite',
    info: 'Elegant met diep gevorkte staart. Symbool van Cantal, zeer talrijk in Margeride.',
    categorie: 'roofvogel',
    regios: ['lozere', 'cantal'],
    zeldzaamheid: 1,
    tip: 'Overal boven open land. Makkelijk te herkennen aan gevorkte roestbruine staart.',
    geluid: 'https://xeno-canto.org/species/Milvus-milvus',
  },
  {
    id: 'steenarend',
    naam: 'Steenarend',
    frans: 'Aigle royal',
    wiki: 'Golden_eagle',
    info: 'Koning van de bergen. Spanwijdte tot 2,2m. Jaagt op marmotten en gemzen.',
    categorie: 'roofvogel',
    regios: ['pyrenees', 'lozere'],
    zeldzaamheid: 2,
    tip: 'Hoge bergwanden en open valleien. Vroege ochtend bij thermiek. Vaak solitair.',
    geluid: 'https://xeno-canto.org/species/Aquila-chrysaetos',
  },
  {
    id: 'slangenarend',
    naam: 'Slangenarend',
    frans: 'Circaète Jean-le-Blanc',
    wiki: 'Short-toed_snake_eagle',
    info: 'Specialist in slangen en hagedissen. Hangt stil in de lucht (bidden). Witte onderkant.',
    categorie: 'roofvogel',
    regios: ['lozere', 'cantal', 'pyrenees'],
    zeldzaamheid: 2,
    tip: 'Zomergast (april-sept). Warme hellingen met struikgewas. Kijk voor biddende roofvogel.',
    geluid: 'https://xeno-canto.org/species/Circaetus-gallicus',
  },
  {
    id: 'blauwe-kiekendief',
    naam: 'Blauwe kiekendief',
    frans: 'Busard Saint-Martin',
    wiki: 'Hen_harrier',
    info: 'Mannetje spookachtig lichtgrijs. Laag glijdend over heide op zoek naar prooi.',
    categorie: 'roofvogel',
    regios: ['cantal'],
    zeldzaamheid: 2,
    tip: 'Open heidevelden en hoogvlaktes Cantal. Schemering is beste tijd.',
    geluid: 'https://xeno-canto.org/species/Circus-cyaneus',
  },
  {
    id: 'oehoe',
    naam: 'Oehoe',
    frans: 'Grand-duc d\'Europe',
    wiki: 'Eurasian_eagle-owl',
    info: 'Grootste Europese uil. Oorpluimen en oranje ogen. Roep draagt kilometers ver.',
    categorie: 'roofvogel',
    regios: ['lozere'],
    zeldzaamheid: 2,
    tip: 'Gorges du Tarn kliffen. Luister bij zonsondergang naar diepe "oehoe" roep.',
    geluid: 'https://xeno-canto.org/species/Bubo-bubo',
  },

  // ============================================
  // ANDERE VOGELS
  // ============================================
  {
    id: 'alpenkraai',
    naam: 'Alpenkraai',
    frans: 'Crave à bec rouge',
    wiki: 'Red-billed_chough',
    info: 'Zwart met opvallend rode snavel en poten. Acrobatische vlieger langs rotswanden.',
    categorie: 'roofvogel',
    regios: ['cantal', 'pyrenees'],
    zeldzaamheid: 2,
    tip: 'Rotswanden en bergtoppen. Vaak in groepen. Luister naar hoge "tsjiii" roep.',
    geluid: 'https://xeno-canto.org/species/Pyrrhocorax-pyrrhocorax',
  },
  {
    id: 'fluiter',
    naam: 'Fluiter',
    frans: 'Pouillot siffleur',
    wiki: 'Wood_warbler',
    info: 'Prachtig zilveren trillende zang in beukenbossen. Geel-groene bovenkant.',
    categorie: 'roofvogel',
    regios: ['lozere'],
    zeldzaamheid: 2,
    tip: 'Beukenbossen Cévennes. Herkenbaar aan afdalende trilzang. Mei-juli.',
    geluid: 'https://xeno-canto.org/species/Phylloscopus-sibilatrix',
  },
  {
    id: 'sneeuwvink',
    naam: 'Sneeuwvink',
    frans: 'Niverolle alpine',
    wiki: 'White-winged_snowfinch',
    info: 'Leeft alleen boven 2000m. Witte vleugelstrepen opvallend in vlucht.',
    categorie: 'roofvogel',
    regios: ['pyrenees'],
    zeldzaamheid: 2,
    tip: 'Alleen boven 2000m bij rotsige toppen. Vaak bij berghutten op zoek naar kruimels.',
    geluid: 'https://xeno-canto.org/species/Montifringilla-nivalis',
  },
  {
    id: 'sneeuwhoen',
    naam: 'Sneeuwhoen',
    frans: 'Lagopède alpin',
    wiki: 'Rock_ptarmigan',
    info: 'Wordt volledig wit in winter. Perfecte camouflage. Bedreigd door klimaatverandering.',
    categorie: 'roofvogel',
    regios: ['pyrenees'],
    zeldzaamheid: 3,
    tip: 'Boven 2200m, rotsige hellingen. Vroege ochtend. Extreem goed gecamoufleerd!',
    geluid: 'https://xeno-canto.org/species/Lagopus-muta',
  },
  {
    id: 'middelste-bonte-specht',
    naam: 'Witrugspe cht',
    frans: 'Pic à dos blanc',
    wiki: 'White-backed_woodpecker',
    info: 'Zeldzaamste specht van Europa. Afhankelijk van oerbossen met dood hout.',
    categorie: 'roofvogel',
    regios: ['pyrenees'],
    zeldzaamheid: 3,
    tip: 'Oude gemengde bossen Pyrénées. Luister naar zacht geroffel. Zeer schuw.',
    geluid: 'https://xeno-canto.org/species/Dendrocopos-leucotos',
  },

  // ============================================
  // ZOOGDIEREN
  // ============================================
  {
    id: 'marmot',
    naam: 'Marmot',
    frans: 'Marmotte alpine',
    wiki: 'Alpine_marmot',
    info: 'Schattig knaagdier van de bergen. Waarschuwingsfluit klinkt als scherp gefluit.',
    categorie: 'zoogdier',
    regios: ['cantal', 'pyrenees'],
    zeldzaamheid: 1,
    tip: 'Hoge weiden boven 1400m. Ochtend en late middag. Luister naar fluitende alarmroep.',
    geluid: null,
  },
  {
    id: 'gems',
    naam: 'Gems',
    frans: 'Chamois',
    wiki: 'Chamois',
    info: 'Bergbewoner Cantal. Sierlijke horentjes, donker winterkleed.',
    categorie: 'zoogdier',
    regios: ['cantal'],
    zeldzaamheid: 2,
    tip: 'Steile hellingen Cantal vulkanen. Vroege ochtend met verrekijker.',
    geluid: null,
  },
  {
    id: 'isard',
    naam: 'Isard (Pyrenese gems)',
    frans: 'Isard',
    wiki: 'Pyrenean_chamois',
    info: 'Pyrenese ondersoort, slanker en sierlijker dan Alpengems. Typisch Pyrenees.',
    categorie: 'zoogdier',
    regios: ['pyrenees'],
    zeldzaamheid: 2,
    tip: 'Bergweiden en rotsige hellingen Pyrénées. Ochtendgloren beste kans.',
    geluid: null,
  },
  {
    id: 'moeflon',
    naam: 'Moeflon',
    frans: 'Mouflon corse',
    wiki: 'Mouflon',
    info: 'Wilde schapen met imposante krulhorens (ram). Herintroductie berggebieden.',
    categorie: 'zoogdier',
    regios: ['cantal', 'pyrenees'],
    zeldzaamheid: 2,
    tip: 'Open bergweiden. Vroege ochtend of schemering. Rammen herkenbaar aan krulhorens.',
    geluid: null,
  },
  {
    id: 'edelhert',
    naam: 'Edelhert',
    frans: 'Cerf élaphe',
    wiki: 'Red_deer',
    info: 'Grootste hert van Europa. Burltijd in september spectaculair in de Pyrénées.',
    categorie: 'zoogdier',
    regios: ['pyrenees'],
    zeldzaamheid: 2,
    tip: 'Bossen en open vlaktes. September = burltijd, luister naar imposant gebulder.',
    geluid: null,
  },
  {
    id: 'europese-genet',
    naam: 'Europese genet',
    frans: 'Genette commune',
    wiki: 'Common_genet',
    info: 'Katachtig roofdier met gevlekte vacht en lange geringde staart. Nachtelijk en zeldzaam in Europa.',
    categorie: 'zoogdier',
    regios: ['lozere', 'pyrenees'],
    zeldzaamheid: 3,
    tip: 'Nachtelijk! Schemering bij bosranden en oude gebouwen. Wildcamera beste optie.',
    geluid: null,
  },
  {
    id: 'bruine-beer',
    naam: 'Bruine beer',
    frans: 'Ours brun',
    wiki: 'Brown_bear',
    info: 'Circa 80 beren in de Pyrénées na herintroductie. Controversieel bij herders.',
    categorie: 'zoogdier',
    regios: ['pyrenees'],
    zeldzaamheid: 3,
    tip: 'Extreem zeldzaam om te zien. Kijk naar sporen: klauwafdrukken, omgewoelde stenen, beer-bomen.',
    geluid: null,
  },
  {
    id: 'desman',
    naam: 'Pyrenese desman',
    frans: 'Desman des Pyrénées',
    wiki: 'Pyrenean_desman',
    info: 'Endemisch voor de Pyrénées! Bizarre snuit, semi-aquatisch. Een van Europa\'s zeldzaamste zoogdieren.',
    categorie: 'zoogdier',
    regios: ['pyrenees'],
    zeldzaamheid: 3,
    tip: 'Koude bergbeken. Nachtelijk en extreem schuw. Eerder geluk dan planning.',
    geluid: null,
  },
  {
    id: 'hermelijn',
    naam: 'Hermelijn',
    frans: 'Hermine',
    wiki: 'Stoat',
    info: 'Klein roofdier, wordt wit in winter met zwart staartpuntje. Razendsnelle jager.',
    categorie: 'zoogdier',
    regios: ['cantal'],
    zeldzaamheid: 2,
    tip: 'Hoge weiden en stenen muurtjes. Snel en nieuwsgierig, blijf stil staan als je er een ziet.',
    geluid: null,
  },
  {
    id: 'europese-bever',
    naam: 'Europese bever',
    frans: 'Castor d\'Europe',
    wiki: 'Eurasian_beaver',
    info: 'Grootste knaagdier van Europa. Herbevolkt de Tarn en zijrivieren. Bouwt dammen.',
    categorie: 'zoogdier',
    regios: ['lozere'],
    zeldzaamheid: 2,
    tip: 'Schemering bij de Tarn rivier. Kijk naar knaagsporen op bomen en V-vormige golfjes.',
    geluid: null,
  },
  {
    id: 'europese-nerts',
    naam: 'Europese nerts',
    frans: 'Vison d\'Europe',
    wiki: 'European_mink',
    info: 'Kritisch bedreigd! Een van de zeldzaamste zoogdieren van Europa. Laatste populaties in ZW-Frankrijk.',
    categorie: 'zoogdier',
    regios: ['pyrenees'],
    zeldzaamheid: 3,
    tip: 'Waterrijke gebieden. Praktisch onmogelijk te spotten — een levenslijst-dier.',
    geluid: null,
  },
  {
    id: 'przewalskipaard',
    naam: 'Przewalskipaard',
    frans: 'Cheval de Przewalski',
    wiki: 'Przewalski%27s_horse',
    info: 'Laatste echte wilde paard. Semi-wilde kudde op Causse Méjean sinds 2004.',
    categorie: 'zoogdier',
    regios: ['lozere'],
    zeldzaamheid: 2,
    tip: 'Causse Méjean, bij Le Villaret. Bezoekcentrum met wandeling naar de kudde.',
    geluid: null,
  },

  // ============================================
  // REPTIELEN & AMFIBIEËN
  // ============================================
  {
    id: 'vuursalamander',
    naam: 'Vuursalamander',
    frans: 'Salamandre tachetée',
    wiki: 'Fire_salamander',
    info: 'Zwart met felgele vlekken. Giftige huidafscheiding. Houdt van vochtige nachten.',
    categorie: 'reptiel_amfibie',
    regios: ['lozere'],
    zeldzaamheid: 1,
    tip: 'Vochtige bossen Cévennes. Na regen, schemering. Kijk op bospaden en bij beekjes.',
    geluid: null,
  },
  {
    id: 'alpenwatersalamander',
    naam: 'Alpenwatersalamander',
    frans: 'Triton alpestre',
    wiki: 'Alpine_newt',
    info: 'Prachtig blauw met oranje buik in broedkleed. Leeft in bergmeertjes.',
    categorie: 'reptiel_amfibie',
    regios: ['cantal'],
    zeldzaamheid: 2,
    tip: 'Bergmeertjes en poelen in vulkaangebied. Voorjaar/vroege zomer in het water.',
    geluid: null,
  },
  {
    id: 'muurhagedis',
    naam: 'Muurhagedis',
    frans: 'Lézard des murailles',
    wiki: 'Common_wall_lizard',
    info: 'Alomtegenwoordig op warme stenen muren en rotsen. Razendsnelle zonanbidder.',
    categorie: 'reptiel_amfibie',
    regios: ['lozere', 'cantal', 'pyrenees'],
    zeldzaamheid: 1,
    tip: 'Elke zonnige stenen muur of rots. Middagwarmte. Makkelijkste reptiel om te spotten.',
    geluid: null,
  },

  // ============================================
  // INSECTEN
  // ============================================
  {
    id: 'apollovlinder',
    naam: 'Apollovlinder',
    frans: 'Apollon',
    wiki: 'Apollo_(butterfly)',
    info: 'Beschermde bergvlinder. Wit met rode oogvlekken. Indicator van gezonde bergweides.',
    categorie: 'insect',
    regios: ['cantal', 'pyrenees'],
    zeldzaamheid: 2,
    tip: 'Bergweides boven 1000m. Zonnige dagen juni-augustus. Langzame, zwevende vlucht.',
    geluid: null,
  },
  {
    id: 'europese-wolfspin',
    naam: 'Europese wolfspin',
    frans: 'Lycose de Narbonne',
    wiki: 'Lycosa_tarantula',
    info: 'Imposante spin tot 3cm. Graaft holen in droge grond. Jaagt actief, maakt geen web.',
    categorie: 'insect',
    regios: ['lozere'],
    zeldzaamheid: 2,
    tip: 'Droge Causses. Kijk naar ronde gaten in de grond (2cm diameter) met zijden rand.',
    geluid: null,
  },

  // ============================================
  // BIJZONDER: PYRENESE GEMS-BOK
  // ============================================
  {
    id: 'pyrenese-steenbok',
    naam: 'Pyrenese steenbok',
    frans: 'Bouquetin ibérique',
    wiki: 'Iberian_ibex',
    info: 'Recent herintroductie vanuit Spanje. Imposante naar achter gebogen horens.',
    categorie: 'zoogdier',
    regios: ['pyrenees'],
    zeldzaamheid: 3,
    tip: 'Hoge rotsige gebieden. Populatie groeit maar nog klein. Geduldige observatie nodig.',
    geluid: null,
  },
];

// Categorie labels en emoji's
export const categorieLabels = {
  roofvogel: { label: 'Vogels', emoji: '🦅' },
  zoogdier: { label: 'Zoogdieren', emoji: '🦌' },
  reptiel_amfibie: { label: 'Reptielen & amfibieën', emoji: '🦎' },
  insect: { label: 'Insecten & spinnen', emoji: '🦋' },
};

// Regio labels en emoji's
export const regioLabels = {
  lozere: { label: 'Lozère', emoji: '🏔️' },
  cantal: { label: 'Cantal', emoji: '🌋' },
  pyrenees: { label: 'Pyrénées', emoji: '🐻' },
};

// Zeldzaamheid labels
export const zeldzaamheidLabels = {
  1: { label: 'Veel voorkomend', emoji: '⭐', kleur: '#4CAF50' },
  2: { label: 'Ongewoon', emoji: '⭐⭐', kleur: '#FF9800' },
  3: { label: 'Zeldzaam', emoji: '⭐⭐⭐', kleur: '#F44336' },
};
