const fs = require('fs');
const path = require('path');

const pagePath = path.join(__dirname, 'src', 'routes', '+page.svelte');
const c = [];

// ============ SCRIPT BLOCK ============
c.push('<script>');
c.push('  import { activePagina, gebruiker, darkMode, toggleDarkMode } from "$lib/stores.js";');
c.push('  import GedeeldeLijst from "$lib/components/GedeeldeLijst.svelte";');
c.push('  import Budget from "$lib/components/Budget.svelte";');
c.push('  import Noodinfo from "$lib/components/Noodinfo.svelte";');
c.push('  import WildlifeChecklist from "$lib/components/WildlifeChecklist.svelte";');
c.push('  import WeerWidget from "$lib/components/WeerWidget.svelte";');
c.push('  import SpotVanDeDag from "$lib/components/SpotVanDeDag.svelte";');
c.push('');
c.push('  const vertrekDatum = new Date("2025-07-14");');
c.push('  const dagen = Math.ceil((vertrekDatum - new Date()) / 86400000);');
c.push('');
c.push('  let meerPagina = $state("");');
c.push('');
c.push('  // Emoji variabelen');
c.push('  const E_VLAG = "\\u{1F1EB}\\u{1F1F7}";');
c.push('  const E_KAL = "\\u{1F5D3}\\uFE0F";');
c.push('  const E_FEEST = "\\u{1F389}";');
c.push('  const E_AUTO = "\\u{1F697}";');
c.push('  const E_DEUR = "\\u{1F6AA}";');
c.push('  const E_CAMPING = "\\u{1F3D5}\\uFE0F";');
c.push('  const E_PIN = "\\u{1F4CD}";');
c.push('  const E_TARGET = "\\u{1F3AF}";');
c.push('  const E_ETEN = "\\u{1F37D}\\uFE0F";');
c.push('  const E_LIJST = "\\u{1F4CB}";');
c.push('  const E_WINKEL = "\\u{1F6D2}";');
c.push('  const E_ZWEM = "\\u{1F3CA}";');
c.push('  const E_VOGEL = "\\u{1F985}";');
c.push('  const E_BOEK = "\\u{1F4D3}";');
c.push('  const E_WARN = "\\u26A0\\uFE0F";');
c.push('  const E_MAAN = "\\u{1F319}";');
c.push('  const E_ZON = "\\u2600\\uFE0F";');
c.push('  const E_PIJL = "\\u2192";');
c.push('');
c.push('  // Route tekst als JS variabele (unicode fix)');
c.push('  const routeTekst = "Loz\\u00E8re " + "\\u2192" + " Cantal " + "\\u2192" + " Pyr\\u00E9n\\u00E9es Ari\\u00E9geoises";');
c.push('');
c.push('  // Aftelling tekst');
c.push('  function getAftelTekst() {');
c.push('    if (dagen > 1) return E_KAL + " Nog " + dagen + " dagen";');
c.push('    if (dagen === 1) return E_KAL + " Nog 1 dag!";');
c.push('    if (dagen === 0) return E_FEEST + " Vandaag vertrekken we!";');
c.push('    return E_AUTO + " We zijn onderweg!";');
c.push('  }');
c.push('');
c.push('  const meerGroepen = [');
c.push('    {');
c.push('      label: "Reis",');
c.push('      items: [');
c.push('        { id:"activiteiten",  emoji: E_TARGET, label:"Activiteiten" },');
c.push('        { id:"zwemplekken",   emoji: E_ZWEM,   label:"Zwemplekken" },');
c.push('        { id:"wildlife",      emoji: E_VOGEL,  label:"Wildlife" },');
c.push('      ]');
c.push('    },');
c.push('    {');
c.push('      label: "Lijsten",');
c.push('      items: [');
c.push('        { id:"boodschappen",  emoji: E_WINKEL, label:"Boodschappen" },');
c.push('        { id:"paklijst",      emoji: E_LIJST,  label:"Paklijst" },');
c.push('        { id:"gerechten",     emoji: E_ETEN,   label:"Gerechten" },');
c.push('      ]');
c.push('    },');
c.push('    {');
c.push('      label: "Overig",');
c.push('      items: [');
c.push('        { id:"dagboek",       emoji: E_BOEK,   label:"Dagboek" },');
c.push('        { id:"noodinfo",      emoji: E_WARN,   label:"Noodinfo" },');
c.push('      ]');
c.push('    }');
c.push('  ];');
c.push('');
c.push('  $effect(() => {');
c.push('    if ($activePagina !== "meer") meerPagina = "";');
c.push('  });');
c.push('');
c.push('  function handleToggleDark() {');
c.push('    toggleDarkMode($gebruiker);');
c.push('  }');
c.push('<\/script>');
c.push('');

// ============ HEADER ============
c.push('<div class="header">');
c.push('  <h1>{E_VLAG} Frankrijk</h1>');
c.push('  {#if $activePagina === "home"}');
c.push('    <p>Hoi {$gebruiker}!</p>');
c.push('  {/if}');
c.push('</div>');
c.push('');

// ============ HOME ============
c.push('{#if $activePagina === "home"}');
c.push('  <div class="page-transition">');
c.push('    <WeerWidget />');
c.push('    <SpotVanDeDag />');
c.push('');
c.push('    <div class="card aftelling-card">');
c.push('      <div class="aftelling-tekst">{getAftelTekst()}</div>');
c.push('      <div class="aftelling-route">{routeTekst}</div>');
c.push('    </div>');
c.push('  </div>');
c.push('');

// ============ CAMPINGS ============
c.push('{:else if $activePagina === "campings"}');
c.push('  <div class="page-transition">');
c.push('    <GedeeldeLijst titel="Campings" emoji={E_CAMPING}');
c.push('      collectie="campings" metLink={true}');
c.push('      placeholder="Naam camping..." />');
c.push('  </div>');
c.push('');

// ============ POI ============
c.push('{:else if $activePagina === "poi"}');
c.push('  <div class="page-transition">');
c.push('    <GedeeldeLijst titel="Bezienswaardigheden" emoji={E_PIN}');
c.push('      collectie="pois" metLink={true}');
c.push('      placeholder="Naam plek..." />');
c.push('  </div>');
c.push('');

// ============ BUDGET ============
c.push('{:else if $activePagina === "budget"}');
c.push('  <div class="page-transition">');
c.push('    <Budget />');
c.push('  </div>');
c.push('');

// ============ MEER MENU ============
c.push('{:else if $activePagina === "meer"}');
c.push('  {#if !meerPagina}');
c.push('    <div class="page-transition meer-menu">');
c.push('      {#each meerGroepen as groep}');
c.push('        <div class="meer-groep">');
c.push('          <div class="meer-groep-label">{groep.label}</div>');
c.push('          <div class="meer-groep-items">');
c.push('            {#each groep.items as o}');
c.push('              <button class="meer-item" onclick={() => meerPagina = o.id}>');
c.push('                <span class="meer-emoji">{o.emoji}</span>');
c.push('                <span class="meer-label">{o.label}</span>');
c.push('                <svg class="meer-arrow" width="16" height="16" viewBox="0 0 16 16" fill="none">');
c.push('                  <path d="M6 4L10 8L6 12" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>');
c.push('                </svg>');
c.push('              </button>');
c.push('            {/each}');
c.push('          </div>');
c.push('        </div>');
c.push('      {/each}');
c.push('');

// ============ INSTELLINGEN ============
c.push('      <div class="meer-groep">');
c.push('        <div class="meer-groep-label">Instellingen</div>');
c.push('        <div class="meer-groep-items">');
c.push('          <button class="dark-toggle-item" onclick={handleToggleDark}>');
c.push('            <span class="dark-toggle-emoji">{$darkMode ? E_ZON : E_MAAN}</span>');
c.push('            <span class="dark-toggle-label">{$darkMode ? "Light mode" : "Dark mode"}</span>');
c.push('            <div class="toggle-track" class:active={$darkMode}>');
c.push('              <div class="toggle-thumb">');
c.push('                {$darkMode ? E_MAAN : E_ZON}');
c.push('              </div>');
c.push('            </div>');
c.push('          </button>');
c.push('        </div>');
c.push('      </div>');
c.push('');

// ============ UITLOGGEN ============
c.push('      <button class="meer-uitloggen" onclick={() => { localStorage.removeItem("naam"); location.reload(); }}>');
c.push('        {E_DEUR} Uitloggen');
c.push('      </button>');
c.push('    </div>');
c.push('');

// ============ SUBPAGINAS ============
c.push('  {:else}');
c.push('    <div class="page-transition">');
c.push('      <button class="terug-btn" onclick={() => meerPagina = ""}>');
c.push('        <svg width="18" height="18" viewBox="0 0 18 18" fill="none">');
c.push('          <path d="M11 4L6 9L11 14" stroke="white" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>');
c.push('        </svg>');
c.push('        Terug');
c.push('      </button>');
c.push('');
c.push('      {#if meerPagina === "activiteiten"}');
c.push('        <GedeeldeLijst titel="Activiteiten" emoji={E_TARGET}');
c.push('          collectie="activiteiten" afvinkbaar={true}');
c.push('          placeholder="Nieuwe activiteit..." />');
c.push('      {:else if meerPagina === "gerechten"}');
c.push('        <GedeeldeLijst titel="Gerechten" emoji={E_ETEN}');
c.push('          collectie="gerechten" afvinkbaar={true}');
c.push('          placeholder="Nieuw gerecht..." />');
c.push('      {:else if meerPagina === "paklijst"}');
c.push('        <GedeeldeLijst titel={"Paklijst (" + $gebruiker + ")"} emoji={E_LIJST}');
c.push('          collectie={"paklijst_" + $gebruiker.toLowerCase()} afvinkbaar={true}');
c.push('          placeholder="Wat moet je inpakken..." />');
c.push('      {:else if meerPagina === "boodschappen"}');
c.push('        <GedeeldeLijst titel="Boodschappen" emoji={E_WINKEL}');
c.push('          collectie="boodschappen" afvinkbaar={true}');
c.push('          placeholder="Wat moet je kopen..." />');
c.push('      {:else if meerPagina === "zwemplekken"}');
c.push('        <GedeeldeLijst titel="Zwemplekken" emoji={E_ZWEM}');
c.push('          collectie="zwemplekken" metLink={true}');
c.push('          placeholder="Rivier, meer of plek..." />');
c.push('      {:else if meerPagina === "wildlife"}');
c.push('        <WildlifeChecklist />');
c.push('      {:else if meerPagina === "dagboek"}');
c.push('        <GedeeldeLijst titel="Dagboek" emoji={E_BOEK}');
c.push('          collectie="dagboek" placeholder="Vandaag..." />');
c.push('      {:else if meerPagina === "noodinfo"}');
c.push('        <Noodinfo />');
c.push('      {/if}');
c.push('    </div>');
c.push('  {/if}');
c.push('{/if}');
c.push('');

// ============ SCOPED STYLES ============
c.push('<style>');
c.push('  /* Aftelling kaart */');
c.push('  .aftelling-card {');
c.push('    text-align: center;');
c.push('    padding: 20px 16px;');
c.push('  }');
c.push('  .aftelling-tekst {');
c.push('    font-size: 1.1rem;');
c.push('    font-weight: 600;');
c.push('    color: var(--heading);');
c.push('  }');
c.push('  .aftelling-route {');
c.push('    margin-top: 6px;');
c.push('    font-size: 0.85rem;');
c.push('    font-weight: 400;');
c.push('    color: var(--nav-text);');
c.push('    letter-spacing: 0.3px;');
c.push('  }');
c.push('');
c.push('  /* Meer menu */');
c.push('  .meer-menu { padding: 16px; }');
c.push('  .meer-groep { margin-bottom: 16px; }');
c.push('  .meer-groep-label {');
c.push('    font-size: 0.72rem; font-weight: 600; color: var(--nav-text);');
c.push('    text-transform: uppercase; letter-spacing: 0.5px; padding: 0 4px 6px 4px;');
c.push('  }');
c.push('  .meer-groep-items {');
c.push('    background: var(--card-bg); border-radius: 14px; overflow: hidden;');
c.push('    box-shadow: 0 1px 4px var(--card-shadow);');
c.push('  }');
c.push('  .meer-item {');
c.push('    width: 100%; display: flex; align-items: center; gap: 14px;');
c.push('    padding: 14px 16px; background: none; border: none;');
c.push('    border-bottom: 1px solid var(--border-subtle); cursor: pointer;');
c.push('    text-align: left; transition: background 0.15s ease;');
c.push('    color: var(--nav-text);');
c.push('  }');
c.push('  .meer-item:last-child { border-bottom: none; }');
c.push('  .meer-item:active { background: var(--hover-bg); }');
c.push('  .meer-emoji { font-size: 1.4rem; flex-shrink: 0; }');
c.push('  .meer-label { flex: 1; font-size: 0.95rem; font-weight: 500; color: var(--tekst); }');
c.push('  .meer-arrow { flex-shrink: 0; }');
c.push('  .meer-uitloggen {');
c.push('    width: 100%; padding: 14px; background: none;');
c.push('    border: 1.5px solid #fecaca; border-radius: 14px;');
c.push('    color: #ef4444; font-size: 0.95rem; font-weight: 500;');
c.push('    cursor: pointer; margin-top: 8px;');
c.push('  }');
c.push('  .meer-uitloggen:active { background: var(--hover-bg); }');
c.push('  .terug-btn {');
c.push('    display: flex; align-items: center; gap: 6px;');
c.push('    margin: 16px; padding: 8px 16px; background: var(--blauw);');
c.push('    color: white; border: none; border-radius: 10px;');
c.push('    font-size: 0.9rem; font-weight: 500; cursor: pointer;');
c.push('  }');
c.push('  .terug-btn:active { opacity: 0.85; }');
c.push('</style>');

fs.writeFileSync(pagePath, c.join('\n'), 'utf8');
console.log('+page.svelte geschreven');
console.log('');
console.log('Fixes:');
console.log('  - Unicode route tekst nu als JS variabele (geen raw escapes meer)');
console.log('  - Aftelling kaart: kleiner, rustiger, consistent font-weight');
console.log('  - Meer menu arrow SVG: stroke="currentColor" (volgt dark mode)');
console.log('  - Alle hardcoded kleuren in scoped styles -> CSS variabelen');
console.log('  - meer-groep-label kleur: var(--nav-text)');
console.log('');
console.log('Test met: npm run dev -- --port 3000');
console.log('Daarna script 2 voor global polish.');