const fs = require('fs');
const path = require('path');

// === Maak src/lib/emojis.js ===
const file = path.join(__dirname, 'src', 'lib', 'emojis.js');
const c = [];

c.push('// Gecentraliseerde emoji constanten');
c.push('// Gebruik: import { E } from "$lib/emojis.js";');
c.push('// In template: {E.CHECK} of {E.EURO}');
c.push('');
c.push('export const E = {');
c.push('  // Algemeen');
c.push('  CHECK: "\\u2705",');
c.push('  KRUIS: "\\u274C",');
c.push('  X: "\\u2715",');
c.push('  UNDO: "\\u21A9\\uFE0F",');
c.push('  EURO: "\\u20AC",');
c.push('  PIJL: "\\u2192",');
c.push('  GRADEN: "\\u00B0",');
c.push('');
c.push('  // Navigatie & UI');
c.push('  ZOEK: "\\u{1F50D}",');
c.push('  FILTER: "\\u{1F3AF}",');
c.push('  PEN: "\\u270F\\uFE0F",');
c.push('  PRULLENBAK: "\\u{1F5D1}\\uFE0F",');
c.push('  KALENDER: "\\u{1F4C5}",');
c.push('');
c.push('  // Budget');
c.push('  GELD: "\\u{1F4B0}",');
c.push('  HANDDRUK: "\\u{1F91D}",');
c.push('  GRAFIEK: "\\u{1F4CA}",');
c.push('  LEEG: "\\u{1F4AD}",');
c.push('');
c.push('  // Wildlife & Natuur');
c.push('  POOT: "\\u{1F43E}",');
c.push('  VOGEL: "\\u{1F985}",');
c.push('  PIN: "\\u{1F4CD}",');
c.push('  NOTITIE: "\\u{1F4DD}",');
c.push('  TIP: "\\u{1F4A1}",');
c.push('  WIKI: "\\u{1F4D6}",');
c.push('  GELUID: "\\u{1F50A}",');
c.push('');
c.push('  // Weer');
c.push('  WEER: "\\u{1F324}\\uFE0F",');
c.push('  DRUPPEL: "\\u{1F4A7}",');
c.push('  WIND: "\\u{1F4A8}",');
c.push('');
c.push('  // Reis');
c.push('  VLAG: "\\u{1F1EB}\\u{1F1F7}",');
c.push('  AUTO: "\\u{1F697}",');
c.push('  FEEST: "\\u{1F389}",');
c.push('  DEUR: "\\u{1F6AA}",');
c.push('  CAMPING: "\\u{1F3D5}\\uFE0F",');
c.push('');
c.push('  // Categorieën');
c.push('  ETEN: "\\u{1F37D}\\uFE0F",');
c.push('  WINKEL: "\\u{1F6D2}",');
c.push('  BENZINE: "\\u26FD",');
c.push('  TOL: "\\u{1F6E3}\\uFE0F",');
c.push('  UITJES: "\\u{1F3AF}",');
c.push('  DOOS: "\\u{1F4E6}",');
c.push('  ZWEM: "\\u{1F3CA}",');
c.push('  LIJST: "\\u{1F4CB}",');
c.push('  BOEK: "\\u{1F4D3}",');
c.push('  WARN: "\\u26A0\\uFE0F",');
c.push('  TARGET: "\\u{1F3AF}",');
c.push('};');

fs.writeFileSync(file, c.join('\n'), 'utf-8');
console.log('src/lib/emojis.js aangemaakt!');
console.log('');
console.log('Je kunt nu in elk component dit doen:');
console.log('  import { E } from "$lib/emojis.js";');
console.log('  // In template: {E.CHECK} {E.EURO} etc.');
console.log('');
console.log('De bestaande components werken nog prima met hun lokale constanten.');
console.log('Bij volgende wijzigingen kun je geleidelijk overstappen op E.xxx');